name: Publish Python Package

on:
  release:
    types:['created']

jobs:
  build-and-publish-PyPi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # 选择你的 Python 版本
        
    - name: Check for README.md changes
      id: check_readme
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qv '^README.md$'; then
          echo "::set-output name=should_publish::true"
        else
          echo "::set-output name=should_publish::false"
        fi

    - name: Install dependencies
      if: steps.check_readme.outputs.should_publish == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      if: steps.check_readme.outputs.should_publish == 'true'
      run: python setup.py sdist bdist_wheel

    - name: Publish package to PyPI
      if: steps.check_readme.outputs.should_publish == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m twine upload dist/*
